# Generated by Django 3.1.7 on 2021-04-12 08:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadmin',
            name='team_id',
            field=models.CharField(default=api.models.generate_id, max_length=8, unique=True),
        ),
    ]
