# Generated by Django 3.1.7 on 2021-04-19 17:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=8)),
                ('player_id', models.CharField(default=api.models.generate_id, max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
    ]
