# Generated by Django 3.1.7 on 2021-04-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=8)),
                ('player_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('team_id', models.CharField(max_length=8)),
                ('team_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ongoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=8)),
                ('player_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('team_id', models.CharField(max_length=8)),
                ('team_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
